name: upscaler
title: Upscaler (Unofficial)
description: |
  Upscaler allows you to upscale and enhance a given image. 
  It is a front-end for Real-ESRGAN ncnn Vulkan.
  (Unofficial Snap)
base: core24
adopt-info: upscaler
compression: lzo
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
  armhf:

parts:
  real-esrgan:
    plugin: nil
    source: https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesrgan-ncnn-vulkan-20220424-ubuntu.zip
    override-build: |
      craftctl default
      install -Dm755 $CRAFT_PART_SRC/realesrgan-ncnn-vulkan -t $CRAFT_PART_INSTALL/usr/bin
      mkdir $CRAFT_PART_INSTALL/usr/bin/models
      mv $CRAFT_PART_SRC/models/*.{bin,param} $CRAFT_PART_INSTALL/usr/bin/models

  upscaler:
    plugin: meson
    source: https://gitlab.gnome.org/World/Upscaler.git
    source-tag: '1.2.2'
    source-depth: 1
    meson-parameters: [ --prefix=/snap/upscaler/current/usr, --buildtype=release ]
    parse-info: [ usr/share/metainfo/io.gitlab.theevilskeleton.Upscaler.metainfo.xml ]
    build-snaps:
      - blueprint-compiler/latest/edge
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/upscaler/current/usr/bin/upscaler
      sed -i 's|https://gitlab.gnome.org/World/Upscaler/-/issues|https://github.com/soumyaDghosh/upscaler-snap/issues|g' $CRAFT_PART_INSTALL/snap/upscaler/current/usr/share/metainfo/io.gitlab.theevilskeleton.Upscaler.metainfo.xml
      sed -i 's|https://matrix.to/#/#Upscaler:gnome.org|https://github.com/soumyaDghosh/upscaler-snap/issues|g' $CRAFT_PART_INSTALL/snap/upscaler/current/usr/share/metainfo/io.gitlab.theevilskeleton.Upscaler.metainfo.xml
    organize:
      snap/upscaler/current: .

  deps:
    after: [upscaler]
    plugin: python
    source: https://github.com/python-cffi/cffi.git
    source-tag: 'v1.15.1'
# ext:updatesnap
#   version-format:
#     lower-than: v1.16.0
    source-depth: 1
    python-packages:
      - vulkan==1.1.99.1
      - pillow==10.0.0
    prime:
      - -bin
      - -pyvenv.cfg
      - -include
      - -lib64
      - -lib
    organize:
      lib/python3.12/site-packages: usr/lib/python3/dist-packages

slots:
  upscaler:
    interface: dbus
    bus: session
    name: io.gitlab.theevilskeleton.Upscaler

apps:
  upscaler:
    command: usr/bin/upscaler
    desktop: usr/share/applications/io.gitlab.theevilskeleton.Upscaler.desktop
    extensions: [ gnome ]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      GDK_DEBUG: portals
    common-id: io.gitlab.theevilskeleton.Upscaler
    plugs:
      - network
      - network-status
      - home
