name: upscaler
title: Upscaler (Unofficial)
description: |
  Upscaler allows you to upscale and enhance a given image.
  It is a front-end for Real-ESRGAN ncnn Vulkan.
  (Unofficial Snap)
base: core24
adopt-info: upscaler
compression: lzo
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  armhf:
parts:
  upscayl-ncnn:
    source: https://github.com/upscayl/upscayl-ncnn/releases/download/20240601-103425/upscayl-bin-20240601-103425-linux.zip
    source-checksum: "sha256/6dad58da39547d64753470ef5a24c4094ce1085b9cb81dabf7e44bd3b7a807a4"
    plugin: nil
    override-build: |
      install -Dm755 $CRAFT_PART_SRC/*/upscayl-bin $CRAFT_PART_INSTALL/usr/bin/upscayl-bin
  vulkan-models:
    source: https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesrgan-ncnn-vulkan-20220424-ubuntu.zip
    source-checksum: "sha256/e5aa6eb131234b87c0c51f82b89390f5e3e642b7b70f2b9bbe95b6a285a40c96"
    plugin: dump
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin/models
      mv $CRAFT_PART_SRC/models/*.{bin,param} $CRAFT_PART_INSTALL/usr/bin/models
  upscaler:
    plugin: meson
    source: https://gitlab.gnome.org/World/Upscaler.git
    source-tag: '1.5.2'
    source-depth: 1
    meson-parameters: [--prefix=/snap/upscaler/current/usr, --buildtype=release]
    parse-info: [usr/share/metainfo/io.gitlab.theevilskeleton.Upscaler.metainfo.xml]
    build-snaps:
      - blueprint-compiler/latest/stable
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/upscaler/current/usr/bin/upscaler
      sed -i 's|https://gitlab.gnome.org/World/Upscaler/-/issues|https://github.com/soumyaDghosh/upscaler-snap/issues|g' $CRAFT_PART_INSTALL/snap/upscaler/current/usr/share/metainfo/io.gitlab.theevilskeleton.Upscaler.metainfo.xml
      sed -i 's|https://matrix.to/#/#Upscaler:gnome.org|https://github.com/soumyaDghosh/upscaler-snap/issues|g' $CRAFT_PART_INSTALL/snap/upscaler/current/usr/share/metainfo/io.gitlab.theevilskeleton.Upscaler.metainfo.xml
    organize:
      snap/upscaler/current: .
  deps:
    after: [upscaler]
    plugin: python
    source: https://github.com/python-cffi/cffi.git
    source-tag: 'v1.17.1'
    source-depth: 1
    python-packages:
      - vulkan==1.3.275.1
      - pillow==11.2.1
    prime:
      - -bin
      - -pyvenv.cfg
      - -include
      - -lib64
      - -lib
    organize:
      lib/python3.12/site-packages: usr/lib/python3/dist-packages
slots:
  upscaler:
    interface: dbus
    bus: session
    name: io.gitlab.theevilskeleton.Upscaler
apps:
  upscaler:
    command: usr/bin/upscaler
    desktop: usr/share/applications/io.gitlab.theevilskeleton.Upscaler.desktop
    extensions: [gnome]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    common-id: io.gitlab.theevilskeleton.Upscaler
    plugs:
      - network
      - network-status
      - home
